{% set name = "dagster_postgres" %}
{% set version = "0.6.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 491cf3bf9e8c065c2db5aad47ae3aea8d4f7cfb5d69922f21760055c579b4450

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dagster {{ version }}
    - psycopg2 2.7.6.1.*

test:
  imports:
    - dagster_postgres

about:
  home: "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-postgres"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "A Dagster integration for postgres"

extra:
  recipe-maintainers:
    - xhochy
